package com.example.myfirstapp;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;

public class Life_Books extends AppCompatActivity {
    private ArrayList<BookItem> bookItems = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_life__books);
        setContentView(R.layout.activity_life__books);
        RecyclerView recyclerView = findViewById(R.id.life_recyclerview);
        recyclerView.setHasFixedSize(true);
        recyclerView.setAdapter(new BookAdapter(bookItems, this));
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
//(int frame, String title, String key_id, String favStatus, int bookimage, String pagesandreviews, String author)
        bookItems.add(new BookItem(R.drawable.container,"The New York Times #1 bestselling book by Pastor Rick Warren that helps you understand and live out the purpose of your life.\n" + "Before you were born, God already planned your life. God longs for you to discover the life he uniquely created you to live--here on earth, and forever in eternity. Let The Purpose Driven Life show you how. As one of the bestselling nonfiction books in history, with more than 35 million copies sold, The Purpose Driven Life is far more than just a book; it's the road map for your spiritual journey. A journey that will transform your life.\n" + "\n" + "Designed to be read in 42 days, each chapter provides a daily meditation and practical steps to help you discover and live out your purpose, starting with exploring three of life's most pressing questions:\n" + "\n" + "The Question of Existence: Why am I alive?\n" + "The Question of Significance: Does my life matter?\n" + "The Question of Purpose: What on earth am I here for?", "The Purpose Driven Life","18","0",R.drawable.life1,"830 page  320 review","By Rick Warren",(float)4.5));
        bookItems.add(new BookItem(R.drawable.container, "In Life Code: The New Rules for Winning in the Real World, six-time New York Times #1 best-selling author Dr. Phil McGraw abandons traditional thinking and tells you the ugly truth about the users, abusers, and overall “bad guys” we all have in our lives. He also reveals the secrets of how they think and how they get to and exploit you and those you love. You’ll gain incredible insight into these negative people, which he refers to as BAITERs (Backstabbers, Abusers, Imposters, Takers, Exploiters, Reckless), and you’ll gain the tools to protect yourself from their assaults. Dr. Phil's new book gives you the “Evil Eight” identifiers so you can see them coming from a mile away, as well as their “Secret Playbook,” which contains the “Nefarious 15” tactics they use to exploit you and take what is yours mentally, physically, socially and professionally. Life Code then focuses on you and your playbook, which contains the “Sweet 16” tactics for winning in the real world.","Life Code","19","0",R.drawable.life2,"1502 page  923 review","By Phil McGraw",(float)5));
        bookItems.add(new BookItem(R.drawable.container, "Humorous, surprising and informative, Dr. Peterson tells us why skateboarding boys and girls must be left alone, what terrible fate awaits those who criticize too easily, and why you should always pet a cat when you meet one on the street.\n" + "What does the nervous system of the lowly lobster have to tell us about standing up straight (with our shoulders back) and about success in life? Why did ancient Egyptians worship the capacity to pay careful attention as the highest of gods? What dreadful paths do people tread when they become resentful, arrogant and vengeful? Dr. Peterson journeys broadly, discussing discipline, freedom, adventure and responsibility, distilling the world's wisdom into 12 practical and profound rules for life. 12 Rules for Life shatters the modern commonplaces of science, faith and human nature, while transforming and ennobling the mind and spirit of its readers.", "12 Rules for Life","20","0",R.drawable.life3,"600 page  200 review","By Jordan B.Peterson",(float)2.5));
        bookItems.add(new BookItem(R.drawable.container,"The science is irrefutable: Small steps circumvent our brains’ built-in resistance to new behaviors. Throughout this book, Dr. Maurer also shows how to visualize virtual change so that real change can come more easily. Why small rewards lead to big returns. And how great discoveries are made by paying attention to the little details most of us overlook. His simple regiment is your path to continuous improvement for anything from losing weight to quitting smoking, paying off debt, or conquering shyness and meeting new people. Rooted in the two-thousand-year-old wisdom of the Tao Te Ching—“The journey of a thousand miles begins with a single step”—here is the way to change your life without fear, without failure, and start on a new path of easy, continuous improvement." ,"One Small Step Can Change Your Life","21","0",R.drawable.life4,"1434 page  660 review","By Robert Maurer",(float)3.5));
        bookItems.add(new BookItem(R.drawable.container,"Designers create worlds and solve problems using design thinking. Look around your office or home—at the tablet or smartphone you may be holding or the chair you are sitting in. Everything in our lives was designed by someone. And every design starts with a problem that a designer or team of designers seeks to solve.\n" + "In this book, Bill Burnett and Dave Evans show us how design thinking can help us create a life that is both meaningful and fulfilling, regardless of who or where we are, what we do or have done for a living, or how young or old we are. The same design thinking responsible for amazing technology, products, and spaces can be used to design and build your career and your life, a life of fulfillment and joy, constantly creative and productive, one that always holds the possibility of surprise.", "Designing Your Life","22","0",R.drawable.life5,"785 page  465 review","By Bill Burnett",(float)4));
        bookItems.add(new BookItem(R.drawable.container,"For more than twenty-five years, Your Money or Your Life has been considered the go-to book for taking back your life by changing your relationship with money. Hundreds of thousands of people have followed this nine-step program, learning to live more deliberately and meaningfully with Vicki Robin’s guidance. This fully revised and updated edition with a foreword by \"the Frugal Guru\" (New Yorker) Mr. Money Mustache is the ultimate makeover of this bestselling classic, ensuring that its time-tested wisdom applies to people of all ages and covers modern topics like investing in index funds, managing revenue streams like side hustles and freelancing, tracking your finances online, and having difficult conversations about money." ,"Your Money or Your Life","23","0",R.drawable.life6,"1912 page  654 review","By Vicki Robin",(float)4.5));

    }
}
