package com.example.myfirstapp;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;

public class Love_Books extends AppCompatActivity {
    private ArrayList<BookItem> bookItems = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_love__books);
     RecyclerView recyclerView = findViewById(R.id.love_recyclerview);
        recyclerView.setHasFixedSize(true);
        recyclerView.setAdapter(new BookAdapter(bookItems, this));
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
//(int frame, String title, String key_id, String favStatus, int bookimage, String pagesandreviews, String author)
        bookItems.add(new BookItem(R.drawable.container,"A New York Times best-selling marriage book making a difference! More than one million copies sold!\n" + "Based on over three decades of counseling, as well as scientific and biblical research, Dr. Emerson Eggerichs and his wife, Sarah, have already taken the Love & Respect message across America and are changing the way couples talk to, think about, and treat each other. What do you want for your marriage? Want some peace? Want to feel close? Want to feel valued? Want to experience marriage the way God intended? Then why not try some Love and Respect.\n" + "A wife has one driving need?to feel loved. When that need is met, she is happy. A husband has one driving need?to feel respected. When that need is met, he is happy. When either of these needs isn’t met, things get crazy. Love & Respect reveals why spouses react negatively to each other, and how they can deal with such conflict quickly, easily, and biblically.\n" + "What readers say about Love & Respect\n" + "“I’ve been married 35 years and have not heard this taught.”\n" + "“This is the key that I have been missing.”\n" + "“You connected all the dots for me.”\n" + "“As a counselor, I have never been so excited about any material.”\n" + "“You’re on to something huge here.”\n" + "Partner Love & Respect with the Love & Respect Workbook for Couples, Individuals, and Groups for an added experience. Love & Respect is also available in Spanish, Amor y Respeto.", "Love and Respect","12","0",R.drawable.love1,"830 page  320 review","By Emerson Eggerichs",(float)4.5));
        bookItems.add(new BookItem(R.drawable.container, "Falling in love is easy. Staying in love—that’s the challenge. How can you keep your relationship fresh and growing amid the demands, conflicts, and just plain boredom of everyday life?\n" + "In the #1 New York Times international bestseller The 5 Love Languages, you’ll discover the secret that has transformed millions of relationships worldwide. Whether your relationship is flourishing or failing, Dr. Gary Chapman’s proven approach to showing and receiving love will help you experience deeper and richer levels of intimacy with your partner—starting today.\n" + "The 5 Love Languages is as practical as it is insightful. Updated to reflect the complexities of relationships today, this new edition reveals intrinsic truths and applies relevant, actionable wisdom in ways that work.\n" + "Includes the Couple's Personal Profile assessment so you can discover your love language and that of your loved one.","The 5 Love Languages","13","0",R.drawable.love2,"1502 page  923 review","By Gary Chapman",(float)5));
        bookItems.add(new BookItem(R.drawable.container, "In this eye-opening guide, Zen monk Thich Nhat Hanh offers timeless insight into the nature of real love. With simplicity, warmth, and directness, he explores the four key aspects of love as described in the Buddhist tradition: lovingkindness, compassion, joy, and freedom—explaining how to experience them in our day-to-day lives. He also emphasizes that in order to love in a real way, we must first learn how to be fully present in our lives, and he offers simple techniques from the Buddhist tradition that anyone can use to establish the conditions of love. \n" + "\n" + "Thich Nhat Hanh, a Vietnamese Zen Buddhist monk, is an internationally known author, poet, scholar, and peace activist who was nominated for the Nobel Peace Prize by Martin Luther King Jr.","True Love","14","0",R.drawable.love3,"600 page  200 review","By Thich Nhat Hanh",(float)2.5));
        bookItems.add(new BookItem(R.drawable.container,"The love she craves, the confidence you need\n" + "In a man's heart is the desire to master what matters. It's nice to get a complement at work or on the court, but nothing beats hearing your spouse say, \"You make me feel loved.\" If you haven't heard that in a while, or you feel like you're not bringing you're A-game relationally, this book is for you.\n" + "The 5 Love Languages® has sold 10 million copies because it is simple, practical, and effective. In this edition, Gary Chapman speaks straight to men about the rewards of learning and speaking their wife's love language. Touched with humor and packed with helpful illustrations and creative pointers, these pages will rouse your inner champion and empower you to master the art of love.\n" + "\"When you express your love for your wife using her primary love language, it's like hitting the sweet spot on a baseball bat or golf club. It just feels right—and the results are impressive.\" —Gary Chapman" ,"The 5 Love Languages for Men","15","0",R.drawable.love4,"1434 page  660 review","By Gary Chapman",(float)3.5));
        bookItems.add(new BookItem(R.drawable.container,"Just when Glennon Doyle Melton was beginning to feel she had it all figured out—three happy children, a doting spouse, and a writing career so successful that her first book catapulted to the top of the New York Times bestseller list—her husband revealed his infidelity and she was forced to realize that nothing was as it seemed. A recovering alcoholic and bulimic, Glennon found that rock bottom was a familiar place. In the midst of crisis, she knew to hold on to what she discovered in recovery: that her deepest pain has always held within it an invitation to a richer life.\n" + "Love Warrior is the story of one marriage, but it is also the story of the healing that is possible for any of us when we refuse to settle for good enough and begin to face pain and love head-on. This astonishing memoir reveals how our ideals of masculinity and femininity can make it impossible for a man and a woman to truly know one another—and it captures the beauty that unfolds when one couple commits to unlearning everything they’ve been taught so that they can finally, after thirteen years of marriage, commit to living true—true to themselves and to each other.\n", "Love Warrior: A Memoir","16","0",R.drawable.love5,"785 page  465 review","By Glennon Doyle",(float)4));
        bookItems.add(new BookItem(R.drawable.container,"You've forgiven a thousand times. You've bent over backwards to make your partner feel loved and accepted. But the only reward for your loyalty has been anger, indifference, infidelity, or abuse. Your spouse may even be ready to walk out the door.\n" + "Do you feel like all is lost? Are you ready to give up? There IS still hope.\n" + "Dr. James Dobson's “tough love” principles have proven to be uniquely valuable and effective. Unlike most approaches to marriage crisis, the strategy in this groundbreaking classic does not require the willing cooperation of both spouses. Love Must Be Tough offers the guidance that gives you the best chance of rekindling romance, renewing your relationship, and drawing your partner back into your arms." ,"Love Must Be Tough","17","0",R.drawable.love6,"1912 page  654 review","By James C. Dobson",(float)4.5));

    }
}
