package com.example.myfirstapp;


import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.text.Editable;
import android.text.TextWatcher;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;

import java.util.ArrayList;


/**
 * A simple {@link Fragment} subclass.
 */
public class SearchFragment extends Fragment {
    private ArrayList<BookItem> bookItems = new ArrayList<>();
    private BookAdapter bookAdapter;

    public View onCreateView(@NonNull LayoutInflater inflater,
                             ViewGroup container, Bundle savedInstanceState) {

        View root = inflater.inflate(R.layout.fragment_search, container, false);
        EditText editText=root.findViewById(R.id.oda);
        RecyclerView recyclerView = root.findViewById(R.id.rty);
        recyclerView.setHasFixedSize(true);
        bookAdapter=new BookAdapter(bookItems,getContext());
        recyclerView.setAdapter( bookAdapter);
        recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
//(int frame, String title, String key_id, String favStatus, int bookimage, String pagesandreviews, String author)


        editText.addTextChangedListener(new TextWatcher() {





            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {

            }

            @Override
            public void afterTextChanged(Editable s) {
                filter(s.toString());



            }
        });


        bookItems.add(new BookItem(R.drawable.container,"        Ferguson says that he saw Manchester United \"change from a conventional football club to what is now a major business enterprise and he never failed to move with the times.\" He says that it was nothing other than his \"man-management\" skills that helped him to deal with the global stars. His relationship with Cristiano Ronaldo has got special importance in the book.[1] He says that he never wanted Ronaldo to join Real Madrid.[2] In this book, he also expresses his feelings about players such as David Beckham and Ryan Giggs.[3]\n", "My Autobiography","0","0",R.drawable.sport1,"830 page  320 review","By Alex Ferguson",(float)4.5));
        bookItems.add(new BookItem(R.drawable.container, "In Wenger: My Life and Lessons in Red and White, world-renowned and revolutionary soccer coach Arsène Wenger finally tells his own story for the very first time.\n" + "Wenger opens up about his life, sharing principles for success on and off the field with lessons on leadership, personal development, and management.\n" + "This book charts his extraordinary career, including his rise from obscurity in France and Japan to his 22 years at the helm of Arsenal Football Club\n" + "• Covers the years of controversy that led up to his resignation in 2018 and his current seat as chief of global football development for FIFA\n" + "• Wenger offers studious reflections on the game and his groundbreaking approach to motivation, mindset, fitness, and the winning edge.\n" + "• He popularized the attacking approach and belief that the game should be entertaining. ","My life and Lessons","1","0",R.drawable.sport2,"1502 page  923 review","By Arsene Wenger",(float)5));
        bookItems.add(new BookItem(R.drawable.container, "Today, more than 68 million children and adolescents participate in sport programs in the United States. Yet despite the growth and popularity of highly-organized athletic competition, controversy still swirls around the role that adults, particularly coaches, play in the world of youth sports. Coaches not only occupy a critical leadership position in the athletic setting, but their influence can extend into other areas of life as well.\n" + "Sport Psychology for Youth Coaches is a practical “how-to” guide that helps coaches use their leadership role to achieve optimal benefits for young athletes, both on and off the field/court.It is designed to help coaches create rewarding experiences for young athletes and provides specific behavioral guidelines that have proven to have positive, and lasting, effects. The authors address a wide range of everyday concerns including motivation, stress reduction, psychological skills, relations with parents, legal responsibilities, and other areas of importance to both coaches and athletes. Using clear examples and real stories, they help coaches hone their own skills so they can bring out the best in their young competitors – in sports and in life.\n" + "No coach should be without this essential guide, whose principles have been successfully applied and tested on thousands of coaches around the world.","Sport Psychology for Youth Coaches","2","0",R.drawable.sport3,"600 page  200 review","By Ronald E.Smith",(float)2.5));
        bookItems.add(new BookItem(R.drawable.container,"Mark Cuban shares his wealth of experience and business savvy in his first published book, HOW TO WIN AT THE SPORT OF BUSINESS.\n" + "\"It's New Year's resolution time, and Mark Cuban's new book offers the rationale for a good one.\" —BUSINESS INSIDER\n" + "Using the greatest material from his popular Blog Maverick, Cuban has collected and updated his postings on business and life to provide a catalog of insider knowledge on what it takes to become a thriving entrepreneur. He tells his own rags-to-riches story of how he went from selling powdered milk and sleeping on friends' couches to owning his own company and becoming a multi-billion dollar success story. His unconventional yet highly effective ideas on how to build a successful business offer entrepreneurs at any stage of their careers a huge edge over their competitors.\n" + "\"In short, [HOW TO WIN AT THE SPORT OF BUSINESS] exceeded...expectations. Short chapters...got right to the point and were not filled with 'stuffing'.\" —HUFFINGTON POST" ,"How To Win","3","0",R.drawable.sport4,"1434 page  660 review","By Mark Cuban",(float)3.5));
        bookItems.add(new BookItem(R.drawable.container,"The leading textbook in sport and exercise psychology is back in a revised seventh edition, and it again raises the bar with its engaging introduction to the field. Foundations of Sport and Exercise Psychology, Seventh Edition With Web Study Guide, offers both students and new practitioners a comprehensive view of sport and exercise psychology, drawing connections between research and practice and capturing the excitement of the world of sport and exercise.\n" + "Internationally respected authors Robert Weinberg and Daniel Gould continue to gather and incorporate feedback from teachers and students with each edition, building a text that addresses emerging trends and remains relevant and up to date. In-depth learning aids have been refreshed, including chapter objectives and summaries, sidebars, key terms, key points, and discussion questions to help students think more critically about applying the material. Other updates to the seventh edition ", "Foundations of Sport and Exercise","4","0",R.drawable.sport5,"785 page  465 review","By Robert S. Weinberg",(float)4));
        bookItems.add(new BookItem(R.drawable.container," All eyes are on Brazil this year as it plays host to the World Cup. Over the course of the competition 32 teams will vie to become soccer champions and national heroes. While the United States is making another appearance at the highest level of the Beautiful Game, they’re not expected to win it all. What’s much more likely is that the Red, White, and Blue will have gone to war with the country that does take home the prize. Aside from love of soccer, most of the teams playing this year have a common bond in the form of U.S. military intervention in their homelands. Sometimes for better, sometimes for worse, sometimes just because. One thing's for sure...the list is long." ,"Soccer By Other Means","5","0",R.drawable.sport6,"1912 page  654 review","By Robert T. Belie",(float)4.5));
        bookItems.add(new BookItem(R.drawable.container,"A landmark volume in science writing by one of the great minds of our time, Stephen Hawking’s book explores such profound questions as: How did the universe begin—and what made its start possible? Does time always flow forward? Is the universe unending—or are there boundaries? Are there other dimensions in space? What will happen when it all ends?\n" + "Told in language we all can understand, A Brief History of Time plunges into the exotic realms of black holes and quarks, of antimatter and “arrows of time,” of the big bang and a bigger God—where the possibilities are wondrous and unexpected. With exciting images and profound imagination, Stephen Hawking brings us closer to the ultimate secrets at the very heart of creation.", "A Brief History of Time","6","0",R.drawable.time1,"830 page  320 review","By Stephen Hawking",(float)4.5));
        bookItems.add(new BookItem(R.drawable.container, "It’s a simple equation--the better you use your time, the more you will accomplish, and the greater you will succeed. But the rollout of this basic theory isn’t so simple, is it? In Time Management, business author and success expert Brian Tracy says it is!In this indispensable, pocket-sized guide, Tracy reveals 21 proven time management techniques you can use immediately to gain two or more productive hours every day. Two or more! Every day!!By learning the strategies that Tracy himself has identified as the most effective and employed personally, readers having trouble fitting everything the day brings them inside a 24-hour window will learn how to:• Handle endless interruptions, meetings, emails, and phone calls • Identify your key result areas • Allocate enough time for top priority responsibilities • Batch similar tasks to preserve focus and make the most of each minute • Overcome procrastination • Determine what to delegate and what to eliminate • Utilize Program Evaluation and Review Techniques to work backward from the future . . . and ensure your most important goals are met • And moreFilled with Brian Tracy's trademark wisdom, this invaluable, time-creating resource will help you get more done, in less time . . . and with much less stress.","Time Management ","7","0",R.drawable.time2,"1502 page  923 review","By Brian Tracy",(float)5));
        bookItems.add(new BookItem(R.drawable.container, "A national bestseller when it first appeared in 1963, The Fire Next Time galvanized the nation, gave passionate voice to the emerging civil rights movement—and still lights the way to understanding race in America today.  \n" + "\"Basically the finest essay I’ve ever read. . . . Baldwin refused to hold anyone’s hand. He was both direct and beautiful all at once. He did not seem to write to convince you. He wrote beyond you.” --Ta-Nehisi Coates\n" + " At once a powerful evocation of James Baldwin's early life in Harlem and a disturbing examination of the consequences of racial injustice, the book is an intensely personal and provocative document from the iconic author of If Beale Street Could Talk and Go Tell It on the Mountain. It consists of two \"letters,\" written on the occasion of the centennial of the Emancipation Proclamation, that exhort Americans, both black and white, to attack the terrible legacy of racism. Described by The New York Times Book Review as \"sermon, ultimatum, confession, deposition, testament, and chronicle...all presented in searing, brilliant prose,\" The Fire Next Time stands as a classic of literature.\n","The Fire Next Time","8","0",R.drawable.time3,"600 page  200 review","By James Baldwin",(float)2.5));
        bookItems.add(new BookItem(R.drawable.container,"Nobody ever looked at an empty calendar and said, \"The best way to spend this time is by cramming it full of meetings!\" or got to work in the morning and thought, Today I'll spend hours on Facebook! Yet that's exactly what we do. Why?\n" + "In a world where information refreshes endlessly and the workday feels like a race to react to other people's priorities faster, frazzled and distracted has become our default position. But what if the exhaustion of constant busyness wasn't mandatory? What if you could step off the hamster wheel and start taking control of your time and attention? That's what this book is about." ,"Make Time","9","0",R.drawable.time4,"1434 page  660 review","By Jake Knapp",(float)3.5));
        bookItems.add(new BookItem(R.drawable.container,"Heartbreaking, funny, and beautifully written, The Absolutely True Diary of a Part-Time Indian, which is based on the author's own experiences, coupled with poignant drawings by Ellen Forney that reflect the character's art, chronicles the contemporary adolescence of one Native American boy as he attempts to break away from the life he was destined to live.\n" + "With a forward by Markus Zusak, interviews with Sherman Alexie and Ellen Forney, and four-color interior art throughout, this edition is perfect for fans and collectors alike.", "The Absolutely True Diary","10","0",R.drawable.time5,"785 page  465 review","By Sherman Alexie",(float)4));
        bookItems.add(new BookItem(R.drawable.container,"A gripping true story of survival, bravery, and honor in the vast Arctic wilderness during World War II, from Mitchell Zuckoff, the author of New York Times bestseller Lost in Shangri-La\n" + "On November 5, 1942, a US cargo plane slammed into the Greenland Ice Cap. Four days later, the B-17 assigned to the search-and-rescue mission became lost in a blinding storm and also crashed. Miraculously, all nine men on board survived, and the US military launched a daring rescue operation. But after picking up one man, the Grumman Duck amphibious plane flew into a severe storm and vanished.\n" + "Frozen in Time tells the story of these crashes and the fate of the survivors, bringing vividly to life their battle to endure 148 days of the brutal Arctic winter, until an expedition headed by famed Arctic explorer Bernt Balchen brought them to safety. Mitchell Zuckoff takes the reader deep into the most hostile environment on earth, through hurricane-force winds, vicious blizzards, and subzero temperatures.\n" + "Moving forward to today, he recounts the efforts of the Coast Guard and North South Polar Inc.—led by indefatigable dreamer Lou Sapienza—who worked for years to solve the mystery of the Duck’s last flight and recover the remains of its crew." ,"Frozen in Time","11","0",R.drawable.time6,"1912 page  654 review","By Mitchell Zuckoff",(float)4.5));
        bookItems.add(new BookItem(R.drawable.container,"A New York Times best-selling marriage book making a difference! More than one million copies sold!\n" + "Based on over three decades of counseling, as well as scientific and biblical research, Dr. Emerson Eggerichs and his wife, Sarah, have already taken the Love & Respect message across America and are changing the way couples talk to, think about, and treat each other. What do you want for your marriage? Want some peace? Want to feel close? Want to feel valued? Want to experience marriage the way God intended? Then why not try some Love and Respect.\n" + "A wife has one driving need?to feel loved. When that need is met, she is happy. A husband has one driving need?to feel respected. When that need is met, he is happy. When either of these needs isn’t met, things get crazy. Love & Respect reveals why spouses react negatively to each other, and how they can deal with such conflict quickly, easily, and biblically.\n" + "What readers say about Love & Respect\n" + "“I’ve been married 35 years and have not heard this taught.”\n" + "“This is the key that I have been missing.”\n" + "“You connected all the dots for me.”\n" + "“As a counselor, I have never been so excited about any material.”\n" + "“You’re on to something huge here.”\n" + "Partner Love & Respect with the Love & Respect Workbook for Couples, Individuals, and Groups for an added experience. Love & Respect is also available in Spanish, Amor y Respeto.", "Love and Respect","12","0",R.drawable.love1,"830 page  320 review","By Emerson Eggerichs",(float)4.5));
        bookItems.add(new BookItem(R.drawable.container, "Falling in love is easy. Staying in love—that’s the challenge. How can you keep your relationship fresh and growing amid the demands, conflicts, and just plain boredom of everyday life?\n" + "In the #1 New York Times international bestseller The 5 Love Languages, you’ll discover the secret that has transformed millions of relationships worldwide. Whether your relationship is flourishing or failing, Dr. Gary Chapman’s proven approach to showing and receiving love will help you experience deeper and richer levels of intimacy with your partner—starting today.\n" + "The 5 Love Languages is as practical as it is insightful. Updated to reflect the complexities of relationships today, this new edition reveals intrinsic truths and applies relevant, actionable wisdom in ways that work.\n" + "Includes the Couple's Personal Profile assessment so you can discover your love language and that of your loved one.","The 5 Love Languages","13","0",R.drawable.love2,"1502 page  923 review","By Gary Chapman",(float)5));
        bookItems.add(new BookItem(R.drawable.container, "In this eye-opening guide, Zen monk Thich Nhat Hanh offers timeless insight into the nature of real love. With simplicity, warmth, and directness, he explores the four key aspects of love as described in the Buddhist tradition: lovingkindness, compassion, joy, and freedom—explaining how to experience them in our day-to-day lives. He also emphasizes that in order to love in a real way, we must first learn how to be fully present in our lives, and he offers simple techniques from the Buddhist tradition that anyone can use to establish the conditions of love. \n" + "\n" + "Thich Nhat Hanh, a Vietnamese Zen Buddhist monk, is an internationally known author, poet, scholar, and peace activist who was nominated for the Nobel Peace Prize by Martin Luther King Jr.","True Love","14","0",R.drawable.love3,"600 page  200 review","By Thich Nhat Hanh",(float)2.5));
        bookItems.add(new BookItem(R.drawable.container,"The love she craves, the confidence you need\n" + "In a man's heart is the desire to master what matters. It's nice to get a complement at work or on the court, but nothing beats hearing your spouse say, \"You make me feel loved.\" If you haven't heard that in a while, or you feel like you're not bringing you're A-game relationally, this book is for you.\n" + "The 5 Love Languages® has sold 10 million copies because it is simple, practical, and effective. In this edition, Gary Chapman speaks straight to men about the rewards of learning and speaking their wife's love language. Touched with humor and packed with helpful illustrations and creative pointers, these pages will rouse your inner champion and empower you to master the art of love.\n" + "\"When you express your love for your wife using her primary love language, it's like hitting the sweet spot on a baseball bat or golf club. It just feels right—and the results are impressive.\" —Gary Chapman" ,"The 5 Love Languages for Men","15","0",R.drawable.love4,"1434 page  660 review","By Gary Chapman",(float)3.5));
        bookItems.add(new BookItem(R.drawable.container,"Just when Glennon Doyle Melton was beginning to feel she had it all figured out—three happy children, a doting spouse, and a writing career so successful that her first book catapulted to the top of the New York Times bestseller list—her husband revealed his infidelity and she was forced to realize that nothing was as it seemed. A recovering alcoholic and bulimic, Glennon found that rock bottom was a familiar place. In the midst of crisis, she knew to hold on to what she discovered in recovery: that her deepest pain has always held within it an invitation to a richer life.\n" + "Love Warrior is the story of one marriage, but it is also the story of the healing that is possible for any of us when we refuse to settle for good enough and begin to face pain and love head-on. This astonishing memoir reveals how our ideals of masculinity and femininity can make it impossible for a man and a woman to truly know one another—and it captures the beauty that unfolds when one couple commits to unlearning everything they’ve been taught so that they can finally, after thirteen years of marriage, commit to living true—true to themselves and to each other.\n", "Love Warrior: A Memoir","16","0",R.drawable.love5,"785 page  465 review","By Glennon Doyle",(float)4));
        bookItems.add(new BookItem(R.drawable.container,"You've forgiven a thousand times. You've bent over backwards to make your partner feel loved and accepted. But the only reward for your loyalty has been anger, indifference, infidelity, or abuse. Your spouse may even be ready to walk out the door.\n" + "Do you feel like all is lost? Are you ready to give up? There IS still hope.\n" + "Dr. James Dobson's “tough love” principles have proven to be uniquely valuable and effective. Unlike most approaches to marriage crisis, the strategy in this groundbreaking classic does not require the willing cooperation of both spouses. Love Must Be Tough offers the guidance that gives you the best chance of rekindling romance, renewing your relationship, and drawing your partner back into your arms." ,"Love Must Be Tough","17","0",R.drawable.love6,"1912 page  654 review","By James C. Dobson",(float)4.5));
        bookItems.add(new BookItem(R.drawable.container,"The New York Times #1 bestselling book by Pastor Rick Warren that helps you understand and live out the purpose of your life.\n" + "Before you were born, God already planned your life. God longs for you to discover the life he uniquely created you to live--here on earth, and forever in eternity. Let The Purpose Driven Life show you how. As one of the bestselling nonfiction books in history, with more than 35 million copies sold, The Purpose Driven Life is far more than just a book; it's the road map for your spiritual journey. A journey that will transform your life.\n" + "\n" + "Designed to be read in 42 days, each chapter provides a daily meditation and practical steps to help you discover and live out your purpose, starting with exploring three of life's most pressing questions:\n" + "\n" + "The Question of Existence: Why am I alive?\n" + "The Question of Significance: Does my life matter?\n" + "The Question of Purpose: What on earth am I here for?", "The Purpose Driven Life","18","0",R.drawable.life1,"830 page  320 review","By Rick Warren",(float)4.5));
        bookItems.add(new BookItem(R.drawable.container, "In Life Code: The New Rules for Winning in the Real World, six-time New York Times #1 best-selling author Dr. Phil McGraw abandons traditional thinking and tells you the ugly truth about the users, abusers, and overall “bad guys” we all have in our lives. He also reveals the secrets of how they think and how they get to and exploit you and those you love. You’ll gain incredible insight into these negative people, which he refers to as BAITERs (Backstabbers, Abusers, Imposters, Takers, Exploiters, Reckless), and you’ll gain the tools to protect yourself from their assaults. Dr. Phil's new book gives you the “Evil Eight” identifiers so you can see them coming from a mile away, as well as their “Secret Playbook,” which contains the “Nefarious 15” tactics they use to exploit you and take what is yours mentally, physically, socially and professionally. Life Code then focuses on you and your playbook, which contains the “Sweet 16” tactics for winning in the real world.","Life Code","19","0",R.drawable.life2,"1502 page  923 review","By Phil McGraw",(float)5));
        bookItems.add(new BookItem(R.drawable.container, "Humorous, surprising and informative, Dr. Peterson tells us why skateboarding boys and girls must be left alone, what terrible fate awaits those who criticize too easily, and why you should always pet a cat when you meet one on the street.\n" + "What does the nervous system of the lowly lobster have to tell us about standing up straight (with our shoulders back) and about success in life? Why did ancient Egyptians worship the capacity to pay careful attention as the highest of gods? What dreadful paths do people tread when they become resentful, arrogant and vengeful? Dr. Peterson journeys broadly, discussing discipline, freedom, adventure and responsibility, distilling the world's wisdom into 12 practical and profound rules for life. 12 Rules for Life shatters the modern commonplaces of science, faith and human nature, while transforming and ennobling the mind and spirit of its readers.", "12 Rules for Life","20","0",R.drawable.life3,"600 page  200 review","By Jordan B.Peterson",(float)2.5));
        bookItems.add(new BookItem(R.drawable.container,"The science is irrefutable: Small steps circumvent our brains’ built-in resistance to new behaviors. Throughout this book, Dr. Maurer also shows how to visualize virtual change so that real change can come more easily. Why small rewards lead to big returns. And how great discoveries are made by paying attention to the little details most of us overlook. His simple regiment is your path to continuous improvement for anything from losing weight to quitting smoking, paying off debt, or conquering shyness and meeting new people. Rooted in the two-thousand-year-old wisdom of the Tao Te Ching—“The journey of a thousand miles begins with a single step”—here is the way to change your life without fear, without failure, and start on a new path of easy, continuous improvement." ,"One Small Step Can Change Your Life","21","0",R.drawable.life4,"1434 page  660 review","By Robert Maurer",(float)3.5));
        bookItems.add(new BookItem(R.drawable.container,"Designers create worlds and solve problems using design thinking. Look around your office or home—at the tablet or smartphone you may be holding or the chair you are sitting in. Everything in our lives was designed by someone. And every design starts with a problem that a designer or team of designers seeks to solve.\n" + "In this book, Bill Burnett and Dave Evans show us how design thinking can help us create a life that is both meaningful and fulfilling, regardless of who or where we are, what we do or have done for a living, or how young or old we are. The same design thinking responsible for amazing technology, products, and spaces can be used to design and build your career and your life, a life of fulfillment and joy, constantly creative and productive, one that always holds the possibility of surprise.", "Designing Your Life","22","0",R.drawable.life5,"785 page  465 review","By Bill Burnett",(float)4));
        bookItems.add(new BookItem(R.drawable.container,"For more than twenty-five years, Your Money or Your Life has been considered the go-to book for taking back your life by changing your relationship with money. Hundreds of thousands of people have followed this nine-step program, learning to live more deliberately and meaningfully with Vicki Robin’s guidance. This fully revised and updated edition with a foreword by \"the Frugal Guru\" (New Yorker) Mr. Money Mustache is the ultimate makeover of this bestselling classic, ensuring that its time-tested wisdom applies to people of all ages and covers modern topics like investing in index funds, managing revenue streams like side hustles and freelancing, tracking your finances online, and having difficult conversations about money." ,"Your Money or Your Life","23","0",R.drawable.life6,"1912 page  654 review","By Vicki Robin",(float)4.5));






        return root;

    }
    private void filter(String text){
        ArrayList<BookItem>filteredList=new ArrayList<>();
        for(BookItem item:bookItems){
            if(item.getTitle().toLowerCase().contains(text.toLowerCase())){
                filteredList.add(item);

            }


        }
        bookAdapter.filterList(filteredList);



    }
}

