package com.example.myfirstapp;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;

public class Sport_Books extends AppCompatActivity {
    private ArrayList<BookItem> bookItems = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sport__books);
        RecyclerView recyclerView = findViewById(R.id.sport_recyclerview);
        recyclerView.setHasFixedSize(true);
        recyclerView.setAdapter(new BookAdapter(bookItems, this));
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
//(int frame, String title, String key_id, String favStatus, int bookimage, String pagesandreviews, String author)
        bookItems.add(new BookItem(R.drawable.container,"        Ferguson says that he saw Manchester United \"change from a conventional football club to what is now a major business enterprise and he never failed to move with the times.\" He says that it was nothing other than his \"man-management\" skills that helped him to deal with the global stars. His relationship with Cristiano Ronaldo has got special importance in the book.[1] He says that he never wanted Ronaldo to join Real Madrid.[2] In this book, he also expresses his feelings about players such as David Beckham and Ryan Giggs.[3]\n", "My Autobiography","0","0",R.drawable.sport1,"830 page  320 review","By Alex Ferguson",(float)4.5));
        bookItems.add(new BookItem(R.drawable.container, "In Wenger: My Life and Lessons in Red and White, world-renowned and revolutionary soccer coach Arsène Wenger finally tells his own story for the very first time.\n" + "Wenger opens up about his life, sharing principles for success on and off the field with lessons on leadership, personal development, and management.\n" + "This book charts his extraordinary career, including his rise from obscurity in France and Japan to his 22 years at the helm of Arsenal Football Club\n" + "• Covers the years of controversy that led up to his resignation in 2018 and his current seat as chief of global football development for FIFA\n" + "• Wenger offers studious reflections on the game and his groundbreaking approach to motivation, mindset, fitness, and the winning edge.\n" + "• He popularized the attacking approach and belief that the game should be entertaining. ","My life and Lessons","1","0",R.drawable.sport2,"1502 page  923 review","By Arsene Wenger",(float)5));
        bookItems.add(new BookItem(R.drawable.container, "Today, more than 68 million children and adolescents participate in sport programs in the United States. Yet despite the growth and popularity of highly-organized athletic competition, controversy still swirls around the role that adults, particularly coaches, play in the world of youth sports. Coaches not only occupy a critical leadership position in the athletic setting, but their influence can extend into other areas of life as well.\n" + "Sport Psychology for Youth Coaches is a practical “how-to” guide that helps coaches use their leadership role to achieve optimal benefits for young athletes, both on and off the field/court.It is designed to help coaches create rewarding experiences for young athletes and provides specific behavioral guidelines that have proven to have positive, and lasting, effects. The authors address a wide range of everyday concerns including motivation, stress reduction, psychological skills, relations with parents, legal responsibilities, and other areas of importance to both coaches and athletes. Using clear examples and real stories, they help coaches hone their own skills so they can bring out the best in their young competitors – in sports and in life.\n" + "No coach should be without this essential guide, whose principles have been successfully applied and tested on thousands of coaches around the world.","Sport Psychology for Youth Coaches","2","0",R.drawable.sport3,"600 page  200 review","By Ronald E.Smith",(float)2.5));
        bookItems.add(new BookItem(R.drawable.container,"Mark Cuban shares his wealth of experience and business savvy in his first published book, HOW TO WIN AT THE SPORT OF BUSINESS.\n" + "\"It's New Year's resolution time, and Mark Cuban's new book offers the rationale for a good one.\" —BUSINESS INSIDER\n" + "Using the greatest material from his popular Blog Maverick, Cuban has collected and updated his postings on business and life to provide a catalog of insider knowledge on what it takes to become a thriving entrepreneur. He tells his own rags-to-riches story of how he went from selling powdered milk and sleeping on friends' couches to owning his own company and becoming a multi-billion dollar success story. His unconventional yet highly effective ideas on how to build a successful business offer entrepreneurs at any stage of their careers a huge edge over their competitors.\n" + "\"In short, [HOW TO WIN AT THE SPORT OF BUSINESS] exceeded...expectations. Short chapters...got right to the point and were not filled with 'stuffing'.\" —HUFFINGTON POST" ,"How To Win","3","0",R.drawable.sport4,"1434 page  660 review","By Mark Cuban",(float)3.5));
        bookItems.add(new BookItem(R.drawable.container,"The leading textbook in sport and exercise psychology is back in a revised seventh edition, and it again raises the bar with its engaging introduction to the field. Foundations of Sport and Exercise Psychology, Seventh Edition With Web Study Guide, offers both students and new practitioners a comprehensive view of sport and exercise psychology, drawing connections between research and practice and capturing the excitement of the world of sport and exercise.\n" + "Internationally respected authors Robert Weinberg and Daniel Gould continue to gather and incorporate feedback from teachers and students with each edition, building a text that addresses emerging trends and remains relevant and up to date. In-depth learning aids have been refreshed, including chapter objectives and summaries, sidebars, key terms, key points, and discussion questions to help students think more critically about applying the material. Other updates to the seventh edition ", "Foundations of Sport and Exercise","4","0",R.drawable.sport5,"785 page  465 review","By Robert S. Weinberg",(float)4));
        bookItems.add(new BookItem(R.drawable.container," All eyes are on Brazil this year as it plays host to the World Cup. Over the course of the competition 32 teams will vie to become soccer champions and national heroes. While the United States is making another appearance at the highest level of the Beautiful Game, they’re not expected to win it all. What’s much more likely is that the Red, White, and Blue will have gone to war with the country that does take home the prize. Aside from love of soccer, most of the teams playing this year have a common bond in the form of U.S. military intervention in their homelands. Sometimes for better, sometimes for worse, sometimes just because. One thing's for sure...the list is long." ,"Soccer By Other Means","5","0",R.drawable.sport6,"1912 page  654 review","By Robert T. Belie",(float)4.5));

    }
}
